title: Tutorial de React
description: Tutorial de React
theme: just-the-docs

url: https://aavendan.github.io/react

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
